export const FONT_FAMILIES: Record<string, string> = {
  'Inter': 'Inter, sans-serif',
  'Roboto': 'Roboto, sans-serif',
  'Open Sans': 'Open Sans, sans-serif',
  'Lato': 'Lato, sans-serif',
  'Montserrat': 'Montserrat, sans-serif',
  'Poppins': 'Poppins, sans-serif',
  'Source Sans 3': 'Source Sans 3, sans-serif',
  'Raleway': 'Raleway, sans-serif',
  'Nunito': 'Nunito, sans-serif',
  'Playfair Display': 'Playfair Display, serif',
  'Merriweather': 'Merriweather, serif',
  'Roboto Slab': 'Roboto Slab, serif',
  'PT Sans': 'PT Sans, sans-serif',
  'Oswald': 'Oswald, sans-serif',
  'Roboto Condensed': 'Roboto Condensed, sans-serif',
  'Source Serif 4': 'Source Serif 4, serif',
  'Noto Sans': 'Noto Sans, sans-serif',
  'Ubuntu': 'Ubuntu, sans-serif',
  'Work Sans': 'Work Sans, sans-serif',
  'Quicksand': 'Quicksand, sans-serif',
  'Josefin Sans': 'Josefin Sans, sans-serif',
  'Mukta': 'Mukta, sans-serif',
  'Rubik': 'Rubik, sans-serif',
  'IBM Plex Sans': 'IBM Plex Sans, sans-serif',
  'Barlow': 'Barlow, sans-serif',
  'Mulish': 'Mulish, sans-serif',
  'Comfortaa': 'Comfortaa, cursive',
  'Outfit': 'Outfit, sans-serif',
  'Plus Jakarta Sans': 'Plus Jakarta Sans, sans-serif',
  'Courier Prime': 'Courier Prime, monospace',
  'IBM Plex Mono': 'IBM Plex Mono, monospace',
  'Arial': 'Arial, sans-serif',
  'Helvetica': 'Helvetica, sans-serif',
  'Verdana': 'Verdana, sans-serif',
  'Tahoma': 'Tahoma, sans-serif',
  'Trebuchet MS': 'Trebuchet MS, sans-serif',
  'Times New Roman': 'Times New Roman, serif',
  'Georgia': 'Georgia, serif',
  'Courier New': 'Courier New, monospace',
  'Lucida Console': 'Lucida Console, monospace',
  'Palatino': 'Palatino, serif',
  'Garamond': 'Garamond, serif',
}; 