/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        'inter': ['Inter', 'sans-serif'],
        'roboto': ['Roboto', 'sans-serif'],
        'open-sans': ['Open Sans', 'sans-serif'],
        'lato': ['Lato', 'sans-serif'],
        'montserrat': ['Montserrat', 'sans-serif'],
        'poppins': ['Poppins', 'sans-serif'],
        'source-sans': ['Source Sans 3', 'sans-serif'],
        'raleway': ['Raleway', 'sans-serif'],
        'nunito': ['Nunito', 'sans-serif'],
        'playfair': ['Playfair Display', 'serif'],
        'merriweather': ['Merriweather', 'serif'],
        'roboto-slab': ['Roboto Slab', 'serif'],
        'pt-sans': ['PT Sans', 'sans-serif'],
        'oswald': ['Oswald', 'sans-serif'],
        'roboto-condensed': ['Roboto Condensed', 'sans-serif'],
        'source-serif': ['Source Serif 4', 'serif'],
        'noto-sans': ['Noto Sans', 'sans-serif'],
        'ubuntu': ['Ubuntu', 'sans-serif'],
        'work-sans': ['Work Sans', 'sans-serif'],
        'quicksand': ['Quicksand', 'sans-serif'],
        'josefin-sans': ['Josefin Sans', 'sans-serif'],
        'mukta': ['Mukta', 'sans-serif'],
        'rubik': ['Rubik', 'sans-serif'],
        'ibm-plex-sans': ['IBM Plex Sans', 'sans-serif'],
        'barlow': ['Barlow', 'sans-serif'],
        'mulish': ['Mulish', 'sans-serif'],
        'comfortaa': ['Comfortaa', 'sans-serif'],
        'outfit': ['Outfit', 'sans-serif'],
        'plus-jakarta-sans': ['Plus Jakarta Sans', 'sans-serif']
      },
      colors: {
        dustyPlum: '#6E4A7E',
        lavenderHaze: '#D8C8DC',
        softPeach: '#FFC8A2',
        paleGold: '#F9E79F',
        slateBlue: '#2E4A7D',
        skyGlass: '#89CFEF',
        lightGlass: '#E7F6FF',
        pureWhite: '#FFFFFF',
        charcoalBlack: '#342D2D',
      },
    },
  },
  plugins: [],
}
