name: Deploy to cPanel

on:
  push:
    branches: [ main ]
    paths:
      - 'docs-promptreviews/docs-site/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: docs-promptreviews/docs-site/package-lock.json
        
    - name: Install dependencies
      run: |
        cd docs-promptreviews/docs-site
        npm ci
        
    - name: Build static site
      run: |
        cd docs-promptreviews/docs-site
        npm run build:prod
        
    - name: Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: docs-promptreviews/docs-site/out/
        server-dir: public_html/docs/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env*
