-- Create analytics_events table for analytics
-- CREATE TABLE analytics_events (
--   id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
--   prompt_page_id uuid REFERENCES prompt_pages(id) ON DELETE CASCADE,
--   event_type text NOT NULL, -- 'view', 'copy_submit', etc.
--   platform text,
--   created_at timestamptz DEFAULT now(),
--   user_agent text,
--   ip_address text,
--   session_id text
-- ); 